# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c089fe08d6d99b5291668c8ed8a20f5d16a305f1a48e1c80371e8c5b26d98c5172c8e862ad1f8a8808484d73e8f510ed6a830ed4ee1d35dc8527b81ae38aa4ef

test:
  secret_key_base: dfaa1d1ce51f78bc1f0bcfba24b4486c930343b46f05b932e23d5609b0294ade8f984f44461f9a5f1637d5f56a902e6699008855a0a29611027bcf209f4b3d45

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
